#!/usr/bin/env python3
"""Generate the ResiP configs from the matching DPPO configs."""

import copy
import os
import yaml

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT_NAME = "ft_residual_ppo_diffusion_mlp.yaml"

TASKS = [
    ("cfg/robomimic/finetune/can", "robomimic"),
    ("cfg/robomimic/finetune/lift", "robomimic"),
    ("cfg/robomimic/finetune/square", "robomimic"),
    ("cfg/robomimic/finetune/transport", "robomimic"),
    ("cfg/gym/finetune/kitchen-complete-v0", "gym"),
    ("cfg/gym/finetune/kitchen-partial-v0", "gym"),
    ("cfg/gym/finetune/kitchen-mixed-v0", "gym"),
    # FurnitureBench is the benchmark ResiP was published on
    ("cfg/furniture/finetune/one_leg_med", "furniture"),
    ("cfg/furniture/finetune/lamp_med", "furniture"),
]

# ResiP's src/config/base_residual_rl.yaml
RESIP_TRAIN = {
    "learning_rate_actor": 3e-4,
    "optimizer_betas_actor": [0.9, 0.999],
    "learning_rate_critic": 5e-3,
    "lr_scheduler": {"actor_warmup_steps": 5, "critic_warmup_steps": 0},
    "total_timesteps": 1000000000,
    "update_epochs": 50,
    "num_minibatches": 1,
    "discount": 0.999,
    "gae_lambda": 0.95,
    "norm_adv": True,
    "clip_coef": 0.2,
    "clip_vloss": False,
    "ent_coef": 0.0,
    "vf_coef": 1.0,
    "max_grad_norm": 1.0,
    "target_kl": 0.1,
    "n_iterations_train_only_value": 0,
    "residual_l1": 0.0,
    "residual_l2": 0.0,
}

# ResiP's src/config/actor/residual_diffusion.yaml, in this repo's config vocabulary
RESIP_POLICY = {
    "_target_": "agent.residual.residual_policy.ResidualPolicy",
    "actor_mlp_dims": [256, 256],
    "critic_mlp_dims": [256, 256],
    "actor_activation_type": "ReLU",
    "critic_activation_type": "ReLU",
    "action_scale": 0.1,
    "init_logstd": -1.0,
    "learn_std": False,
    "action_head_std": 0.0,
    "critic_last_layer_std": 0.25,
    "critic_last_layer_bias_const": 0.25,
    "cond_dim": "${eval:'${obs_dim} * ${cond_steps}'}",
    "action_dim": "${action_dim}",
}

# Iteration each task's result is read at; tasks absent from this map are not capped.
REPORTING_ITER = {"transport": 180}

# Minimum checkpoint cadence in iterations; the slowest task saves roughly every 1.4 hours.
MAX_SAVE_FREQ = 10


HEADER = """# ResiP (Ankile et al., arXiv 2407.16677) on {task}.
# Generated by agent/residual/gen_configs.py from {src}; do not hand-edit.
"""


class _Flow(list):
    pass


yaml.add_representer(
    _Flow, lambda d, x: d.represent_sequence("tag:yaml.org,2002:seq", x, flow_style=True)
)


def _flow(o):
    if isinstance(o, dict):
        return {k: _flow(v) for k, v in o.items()}
    if isinstance(o, list):
        inner = [_flow(v) for v in o]
        return _Flow(inner) if all(not isinstance(v, (dict, list)) for v in inner) else inner
    return o


def build(cfg_dir, family):
    src_rel = f"{cfg_dir}/ft_ppo_diffusion_mlp.yaml"
    d = yaml.safe_load(open(os.path.join(REPO, src_rel)))
    task = os.path.basename(cfg_dir)
    out = copy.deepcopy(d)
    act_steps = d["act_steps"]

    # --- top level ---
    out["_target_"] = "agent.residual.train_residual_ppo_agent.TrainResidualPPOAgent"
    out["name"] = out["name"].replace("ft_diffusion_mlp", "ft_residual_ppo").replace(
        "ppo_diffusion_mlp", "residual_ppo"
    )
    if "ft_denoising_steps" in out:
        # Pin ddim_steps before zeroing ft_denoising_steps, or furniture silently changes how the base is sampled.
        if str(out["model"].get("ddim_steps", "")) == "${ft_denoising_steps}":
            out["model"]["ddim_steps"] = d["ft_denoising_steps"]
        out["ft_denoising_steps"] = 0

    # --- env: one environment step per policy call ---
    if family == "furniture":
        out["env"]["specific"]["act_steps"] = 1
    else:
        out["env"]["wrappers"]["multi_step"]["n_action_steps"] = 1

    # --- train: same environment steps per iteration, plus ResiP's block ---
    if family == "furniture":
        # the DPPO config writes n_steps as round(max_episode_steps / act_steps)
        dppo_steps = round(d["env"]["max_episode_steps"] / act_steps)
    else:
        dppo_steps = d["train"]["n_steps"]
    env_steps = dppo_steps * act_steps
    out["train"]["n_steps"] = env_steps
    out["train"]["resip"] = copy.deepcopy(RESIP_TRAIN)

    # RULE 1: cap n_train_itr at the next multiple of 100 above the reporting iteration.
    report = REPORTING_ITER.get(task)
    if report is not None:
        cap = ((report // 100) + 1) * 100 + 1  # 180 -> 201
        if out["train"]["n_train_itr"] > cap:
            out["train"]["n_train_itr"] = cap

    # RULE 2: save often enough to checkpoint inside the wall clock, or a timed-out job loops forever.
    out["train"]["save_model_freq"] = min(out["train"]["save_model_freq"], MAX_SAVE_FREQ)

    # --- model: composed policy; the four PPODiffusion-only keys are inert under VPGDiffusion ---
    out["model"]["_target_"] = "agent.residual.residual_diffusion.ResidualDiffusion"
    out["model"]["act_steps"] = "${act_steps}"
    out["model"]["obs_clip"] = 3.0
    out["model"]["action_clip"] = None
    out["model"]["residual_policy"] = copy.deepcopy(RESIP_POLICY)

    # ---- invariants, asserted here so a broken config can never be written ----
    n_itr, freq = out["train"]["n_train_itr"], out["train"]["save_model_freq"]
    saves = sorted({i for i in range(n_itr) if i % freq == 0} | {n_itr - 1})
    assert freq <= MAX_SAVE_FREQ, (
        f"{task}: save_model_freq {freq} > {MAX_SAVE_FREQ}; a timed-out job could "
        "save nothing and the watchdog would resubmit it forever"
    )
    if report is not None:
        assert n_itr > report, (
            f"{task}: n_train_itr {n_itr} does not reach the reporting iteration {report}"
        )
    assert saves[-1] == n_itr - 1, f"{task}: the final iteration is never checkpointed"
    assert len(saves) >= 10, (
        f"{task}: only {len(saves)} checkpoints over the whole run; too coarse to resume"
    )
    assert out["train"]["n_steps"] % act_steps == 0, (
        f"{task}: train.n_steps must be a whole number of act_steps chunks"
    )
    assert env_steps == dppo_steps * act_steps, f"{task}: env steps per iteration drifted"

    dst = os.path.join(REPO, cfg_dir, OUT_NAME)
    body = yaml.dump(_flow(out), sort_keys=False, default_flow_style=False, width=100)
    with open(dst, "w") as f:
        f.write(HEADER.format(task=task, src=src_rel, env_steps=env_steps) + body)
    print(
        f"wrote {os.path.relpath(dst, REPO)}  "
        f"n_steps={env_steps} env steps, n_train_itr={n_itr}, "
        f"{len(saves)} checkpoints, last at {saves[-1]}"
    )


if __name__ == "__main__":
    for cfg_dir, family in TASKS:
        build(cfg_dir, family)
